[package]
name = "adt_stuff"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pyo3 = { git = "https://github.com/mkovaxx/pyo3.git", rev = "c8fdb80" }

[lib]
name = "rust"
path = "lib.rs"
